dist: xenial

language: python

cache: pip

python:
  - "3.6"
  - "3.7"

before_install:
- pip install poetry
install:
- poetry install
script:
  - poetry run pytest tests/
after_success:
  - coveralls
